name: Deploy to Somee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # hoặc phiên bản bạn dùng

      - name: Restore dependencies
        run: dotnet restore deploy-somee.sln

      - name: Build project
        run: dotnet build HelloSomee.sln --configuration Release

      - name: Publish project
        run: dotnet publish HelloSomee.sln --configuration Release --output ./publish

      - name: Deploy to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp://techmyweb.somee.com/www.techmyweb.somee.com
          username: ${{ secrets.SOMEE_FTP_USER }}
          password: ${{ secrets.SOMEE_FTP_PASS }}
          local-dir: ./publish
